name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Connect and deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: 44.208.23.192
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd vitaCare
            git pull origin main
            cd backend
            npm install
            pm2 restart vitacare-backend || pm2 start server.ts \
              --name vitacare-backend \
              --interpreter ./node_modules/.bin/ts-node
